### ISSUE TITLE
Lightbox not working?

### ISSUE THREAD

**Issue by justdayan** [bassjobsen/jbst#77] opened 2013-11-01 08:59 UTC
Greetings,

i've created a basic gallery, with 3 images. When I click on the images, the gallery isn't opening (this is if i'm logged in or out). However, if I go to customize theme in wp-admin, click on the gallery page, and click on an image, the gallery works. Can we confirm that this is an issue?

**Comment by bassjobsen** [comment] 2013-11-01 11:29
Thanks for posting, i will look to this asap.
Possible duplicate of #48.

**Comment by bassjobsen** [comment] 2013-11-02 22:37
Lightboxes now should work with galleries.
For future we will have to look to more bootstrappy solution i think, like http://ashleydw.github.io/lightbox/ or https://github.com/jbutz/bootstrap-lightbox, see also: http://stackoverflow.com/a/19203506/1596547

To make your galleries more responsive (with Bootstrap's Grids) see: https://github.com/bassjobsen/twitterbootstrap-galleries

**Comment by bassjobsen** [comment] 2013-11-03 22:34
Lightbox shows small version of images only (see: http://www.laagakkerstraat.nl/leny/sample-page/)

**Comment by bassjobsen** [comment] 2013-11-05 21:24
The small version issue was due to some jQuery which set the link url equal to the img url.
To set the link url to the image file the like option of the gallery short code had to be set to `file`. Since wp3.6 this can be done by adding a filter to the short code, see: http://sumobi.com/how-to-filter-shortcodes-in-wordpress-3-6/
the jQuery part has been removed. Adding the `data-lightbox` attribute to the link is now conditional of the lightbox setting in the theme options.

**Closed as completed by bassjobsen** 2013-11-05 21:24 UTC
